

# Production
baseURL = "https://cumulocity.com/docs"

languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Cumulocity documentation"
theme = "c8ydocs"
paginate = 12
# canonifyurls = false
publishDir = "public"
# googleAnalytics = "UA-xxxxxxxx-x"
summaryLength = 30
buildFuture = true
relativeURLs = true

[taxonomies]
  sectors = "sector"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.highlight]
      style = "solarized-dark256"

[[params.author]]
  name = "Carlos Ceia @ Cumulocity"



[params]

  # Global keywords configuration. Following keywords will be add to every pages
  keywords = ["Cumulocity", "Internet of things", "analytics", "devices", "connect"]

  description = "IMPORTANT - This documentation is a PREVIEW of the var-product-c8y-iot 2025 release documentation. The content and its described features and functionalities may be subject to change without further notice until this version is officially released."

  oldguides = "//cumulocity.com/guides/welcome/intro-documentation/"

  # Can be a boolean 'false' or a string (example: 'CD' or a release version like '2024'). This flag displays the admonition stating it is a preview version
  docsPreview = false

  # Display thumbnail image of each post on index pages (false: disabled, true: enabled)
  thumbnailImage = true

  logo = "images/logo-platform.svg"


  # Your favicon path, default is "/favicon.png"
  favicon = "//cumulocity.com/favicon.ico"

  # Content variables for Frontmatter titles
  product_c8y_iot = "Cumulocity"
  company_sag = "Software AG"
  enterprise_tenant = "Enterprise tenant"

  [[params.additionalResources]]
    name = "YouTube"
    link = "https://www.youtube.com/@CumulocityIoT"

  [[params.additionalResources]]
    name = "Tech Community"
    link = "https://techcommunity.cumulocity.com/"

  [[params.additionalResources]]
    name = "Learning Portal"
    link = "https://cumulocity.moodlecloud.com/"

    [[params.additionalResources]]
    name = "Platform status"
    link = "https://status.cumulocity.com/"

    [[params.additionalResources]]
      name = "Company portal"
      link = "https://cumulocity.com/"

  [[params.additionalResources]]
    name = "Product Support"
    link = "https://cumulocity.atlassian.net/servicedesk/customer/portals"


# Customize
  [params.footer]
    copyright = "Cumulocity GmbH | <a href='/legal-notices/imprint/'> Imprint</a> | <a href='/legal-notices/privacy-notice/'>Privacy notice</a>"
    c8ylink = "https://cumulocity.com"
