########################################################################################################################
##     Defines the Edge Custom Resource and the Kubernetes Secrets/ComfigMaps required to install Cumulocity Edge.    ##
########################################################################################################################
---
##
## For details, see https://cumulocity.com/docs/2026/edge/edge-custom-resource-definition/#cumulocitypasswordsecretname
##
apiVersion: v1
kind: Secret
metadata:
  name: c8y-admin-password
  namespace: c8yedge
type: Opaque
stringData:
  INITIAL_C8Y_ADMIN_PASSWORD: <C8Y-ADMIN-PASSWORD>

---
##
## For details, see https://cumulocity.com/docs/2026/edge/edge-custom-resource-definition/#tlssecretname
##

# apiVersion: v1
# kind: Secret
# metadata:
  # name: myown-iot-com-tls
  # namespace: c8yedge
# type: Opaque
# stringData:
  # tls.key: <PRIVATE-KEY>
  # tls.crt: <CERTIFICATE-CHAIN>

---
##
## For details, see https://cumulocity.com/docs/2026/edge/edge-custom-resource-definition/#cloudtenant-tlssecretname
##

# apiVersion: v1
# kind: Secret
# metadata:
  # name: edge-device-tls
  # namespace: c8yedge
# type: Opaque
# stringData:
  # tls.key: <PRIVATE-KEY>
  # tls.crt: <CERTIFICATE-CHAIN>

---
##
## For details, see https://cumulocity.com/docs/2026/edge/edge-custom-resource-definition/#mongodb-credentialssecretname
##

# apiVersion: v1
# kind: Secret
# metadata:
  # name: mongodb-credentials
  # namespace: c8yedge
# type: Opaque
# stringData:
  # MONGODB_DATABASE_ADMIN_USER: databaseAdmin
  # MONGODB_DATABASE_ADMIN_PASSWORD: <DB-ADMIN-PASSWORD>

---
##
## For details, see https://cumulocity.com/docs/2026/edge/installing-edge/#configuring-proxy
##

# apiVersion: v1
# kind: ConfigMap
# metadata:
  # name: custom-environment-variables
  # namespace: c8yedge
# data:
  # http_proxy: <HTTP Proxy URL>
  # https_proxy: <HTTPS Proxy URL>
  # socks_proxy: <SOCKS Proxy URL>
  # no_proxy: 127.0.0.1,::1,localhost,.svc,.cluster.local,cumulocity,<edge domain name, for example, myown.iot.com>,<kubernetes cluster IP range, for example, 10.43.0.0/16>
  # ca.crt: <CA-CERTIFICATES TO TRUST>


########################################################################################################################
##                                        Defines Edge Custom Resource                                                ##
########################################################################################################################
---
##
## This Custom Resource (CR) YAML has the Cumulocity Edge deployment settings.
##
## For more information about the CR specification, 
## see https://cumulocity.com/docs/2026/edge/edge-custom-resource-definition
##

apiVersion: edge.cumulocity.com/v1
kind: CumulocityIoTEdge
metadata:
  ## Name of the Edge deployment.
  name: c8yedge
  ## Namespace name into which you installed the Edge operator. By default, the Edge operator is installed in "c8yedge".
  namespace: c8yedge
spec:
  version: "2026"
  domain: <DOMAIN-NAME>
  licenseKey:  <LICENSE-KEY>
  company: <COMPANY-NAME>
  email: <ADMIN-EMAIL>
  cumulocityPasswordSecretName: c8y-admin-password
  # tlsSecretName: myown-iot-com-tls
  # cloudTenant:
      # domain: <TENANT-ID>.cumulocity.com
      # otp: <ONE-TIME PASSWORD>
      # tlsSecretName: edge-device-tls
  # mongodb:
    # credentialsSecretName: mongodb-credentials
    # resources:
      # requests:
        # storage: 75G
  # storageClassName: <STORAGE-CLASS>
