backend:
  name: git-gateway
  repo: SoftwareAG/c8y-docs
  branch: "change-logs"


# Enable for using the cms locally and run
# `npx netlify-cms-proxy-server` on your local repo
# backend:
#   name: git-gateway

# when using the default proxy server port
local_backend: true

# Enable editorial workflow
publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads


collections:
  #  ============================== 
  # Change logs
  #  ============================== 

  - name: "change_logs"
    label: "Change Logs"
    folder: "content/change-logs"
    description: "Change log entries"
    create: true
    fields:
      - {label: "Date",name: "date",widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}

      - label: Change type
        name: change_type
        widget: ncw-file-relation
        collection: configs
        file: change_type
        target_field: options
        id_field: id
        display_fields: option
        required: false

      - label: Product area
        name: product_area
        widget: ncw-file-relation
        collection: configs
        file: product_area
        target_field: options
        id_field: id
        display_fields: option
        required: false

      - label: Component
        name: component
        widget: ncw-file-relation
        collection: configs
        file: component
        target_field: options
        id_field: id
        display_fields: option
        required: false

      - label: Build artifact
        name: technical_component
        widget: ncw-file-relation
        collection: configs
        file: technical_component
        target_field: options
        id_field: id
        display_fields: option
        required: false
      
      - {label: "Ticket", name: "jira", widget: "string", required: false, hint: "The Jira ticket number, e.g. MTM-50245"}
      - {label: "Version", name: "version", widget: "string", required: false, hint: "Add multiple versions separated by a coma"} # this is for the yearly only and support multiple
      - { label: "Body", name: "body", widget: "markdown"}
        
  - label: Change logs config
    name: configs
    files:
      - name: date_settings
        label: Date settings
        file: data/date_settings.toml
        fields:
          - name: yearly_release
            label: Yearly release
            widget: boolean
            default: false
            hint: If it is a yearly release, switch on
          - name: date
            label: Starting from
            widget: datetime
            hint: Starting date to display the change logs (90 days for change logs)

      - name: product_area
        label: Product Area options
        file: data/productarea.json
        fields:
          - name: options
            label: Options
            widget: list
            fields:
              - label: Option
                name: option
                widget: string
              - label: ID
                name: id
                widget: ncw-id
                prefix: product_area
            
      - name: component
        label: Component options
        file: data/component.json
        fields:
          - name: options
            label: Options
            widget: list
            fields:
              - label: Option
                name: option
                widget: string
              - label: ID
                name: id
                widget: ncw-id
                prefix: component

      - name: change_type
        label: Change type options
        file: data/changetype.json
        fields:
          - name: options
            label: Options
            widget: list
            fields:
              - label: Option
                name: option
                widget: string
              - label: ID
                name: id
                widget: ncw-id
                prefix: change

      - name: technical_component
        label: Build artifacts options
        file: data/technicalcomponent.json
        fields:
          - name: options
            label: Options
            widget: list
            fields:
              - label: Option
                name: option
                widget: string
              - label: ID
                name: id
                widget: ncw-id
                prefix: tc
