########################################################################################################################
#                                         Defines Kubernetes Namespace                                                 #
########################################################################################################################
---
#
# Creates 'cumulocity-iot-edge' namespac, same as the name of this Cumulocity IoT Edge deployment 
#

apiVersion: v1
kind: Namespace
metadata:
  name: cumulocity-iot-edge


########################################################################################################################
#                                         Defines Edge Custom Resource                                                 #
########################################################################################################################
---
#
# This Custom Resource deploys Cumulocity IoT Edge version 1017.0.0 named 'cumulocity-iot-edge', with the below details
#  - myown.iot.com domain with self-signed tls certificates
#  - Cumulocity IoT Core and related pods in 'cumulocity-iot-edge-core' namespace
#  - thin-edge for connecting Edge to Cumulocity IoT cloud for remote management in 'cumulocity-iot-edge-thin-edge' namespace
#  - MongoDB server in the 'cumulocity-iot-edge-mongodb' namespace
#  - Private registry in the 'cumulocity-iot-edge-microservices-registry' namespace
#  - Apama and Smart Rules and other microservices in the 'cumulocity-iot-edge-microservices' namespace
#  - Administration, Cockpit, Device Management and Apama Streaming Analytics applications
#  - Logging components in the 'cumulocity-iot-edge-logging' namespace
#

apiVersion: edge.cumulocity.com/v1
kind: CumulocityIoTEdge
metadata:
  name: cumulocity-iot-edge						# Name this Cumulocity IoT Edge deployment
spec:
  version: 1017.0.0                                     
  licenseKey:  <EDGE-LICENSE-KEY>               # Replace with the Edge license key you received

  company: IoT Company                          # Replace with the company name
  domain: myown.iot.com                         # Replace with the domain of your choice
#  tlsSecretName: myown-iot-com-tls-secret      # Uncomment to supply the TLS Key/Certificates for Edge doamin
  email: myown@iot.com                          # Replace with a valid email, used for admin account

#  Uncomment the below 'cloudTenant' field to connect Cumulocity IoT Edge to a Cumulocity Cloud tenant to manage Edge remotely 
#  cloudTenant:
#    domain: <CLOUD-TENANT-DOMAIN>               # Cumulocity IoT cloud tenant domain e.g. <tenantid>.cumulocity.com
#    tlsSecretName: edge-device-tls-secret       # Secret for supplying the TLS Key/Certificates for Cumulocity IoT Edge to authenticate with Cumulocity cloud tenant as a device 

#  storageClassName: <STORAGE-CLASS-NAME>        # Provide the storage class your Kubernetes administrator provisioned for this deployment

#  Uncomment the below 'core' field to specify resource limits for the Cumulocity IoT core pod
#  core:
#    resources:                                                     
#      limits:
#        cpu: 3000m
#        memory: 6144M

  mongodb:
    credentialsSecretName: mongodb-credentials-secret                # Secret for supplying admin credentials of MongoDB server

#    Uncomment below two fields ('connectionString' and 'tlsSecretName') and provide the necessary details to configure the Cumulocity IoT Edge 
#    with an externally hosted MongoDB server, reachable at <CONNECTION-STRING-URI>     
#    connectionString: <CONNECTION-STRING-URI>                      # URI Format: mongodb://host1[:port1][,...hostN[:portN]] 
#    tlsSecretName: external-mongodb-tls-secret                     # Secret for supplying the Certificate Authority (CA) certificate to trust

#    Uncomment the below 'reseources' field to specify resource limits for the MongoDB server pod
#    resources:                                                     
#      limits:
#        cpu: 3000m
#        memory: 6144M
#      requests:
#        storage: 75G                            # Specify the storage to be reserved by MongoDB server to persist data. If not provided, 75 GB storage is reserved.

#  Uncomment below 'microservices' field to specify resource limits for the apama-ctrl, smartrule, opcua-mgmt-service and device-simulator microservices 
#  microservices:
#    - name: smartrule
#      resources:
#        limits:
#          cpu: 1000m
#          memory: 1024M
#    - name: opcua-mgmt-service
#      resources:
#        limits:
#          cpu: 1000m
#          memory: 1024M
#    - name: device-simulator
#      resources:
#        limits:
#          cpu: 1000m
#          memory: 1024M
#    - name: apama-ctrl
#      resources:
#        limits:
#          cpu: 1000m
#          memory: 1024M

########################################################################################################################
#                                         Defines Kubernetes Secrets                                                   #
########################################################################################################################
---
#
# Secret for supplying the TLS Key/Certificates for Edge domain. Accepts only PEM format.
# This secret is optional. If not provided the Operator will generate self-signed certificates.
# Name of this secret can be supplied in "spec.tlsSecretName" field of Edge CR
#

#apiVersion: v1
#kind: Secret
#metadata:
#  name: myown-iot-com-tls-secret          # Name of the secret. Same value should be supplied to "spec.tlsSecretName" field of Edge CR
#  namespace: cumulocity-iot-edge          # Replace with the Edge CR name you used
#type: Opaque
#stringData:
#  tls.key: <PRIVATE-KEY>                  # Replace with the tls private key for the domain. In PEM format.
#  tls.crt: <CERTIFICATE-CHAIN>            # Replace with the tls certificate chain of the private key for the domain. In PEM format.

---
#
# Secret for supplying the TLS Key/Certificates for Cumulocity IoT Edge to authenticate with Cumulocity cloud tenant as a device. Accepts only PEM format.
# This secret is optional. If not provided the Operator will generate self-signed certificates.
# Name of this secret can be supplied in "spec.cloud.tlsSecretName" field of Edge CR
#

#apiVersion: v1
#kind: Secret
#metadata:
#  name: edge-device-tls-secret            # Name of the secret. Same value should be supplied to "spec.cloud.tlsSecretName" field of Edge CR
#  namespace: cumulocity-iot-edge          # Replace with the Edge CR name you used
#type: Opaque
#stringData:
#  tls.key: <PRIVATE-KEY>                  # Replace with the tls private key. In PEM format.
#  tls.crt: <CERTIFICATE-CHAIN>            # Replace with the tls certificate chain of the private key. In PEM format.

---
#
# Secret for supplying admin credentials of MongoDB server (both operator managed and externally hosted), to the Cumulocity IoT Edge Operator.
# Name of this secret can be supplied to "spec.mongodb.credentialsSecretName" field of Edge CR
#

apiVersion: v1
kind: Secret
metadata:
 name: mongodb-credentials-secret    # Name of the secret. Same value should be supplied to "spec.mongodb.credentialsSecretName" field of Edge CR
 namespace: cumulocity-iot-edge      # Replace with the Edge CR name you used
type: Opaque
stringData:
 MONGODB_DATABASE_ADMIN_USER: <ADMIN-USERNAME>                  # Replace with admin username with which the operator managed MongoDB needs to be configured or the admin username the externally hosted MongoDB server is configured.
 MONGODB_DATABASE_ADMIN_PASSWORD: <ADMIN-PASSWORD>              # Replace with admin password with which the operator managed MongoDB needs to be configured or the admin password the externally hosted MongoDB server is configured.
 
# MONGODB_USER_ADMIN_USER: userAdmin                            # Change if you want to use a different username
# MONGODB_USER_ADMIN_PASSWORD: <USER-ADMIN-PASSWORD>            # If not provided, the password defaults to value provided in the field MONGODB_DATABASE_ADMIN_PASSWORD
 
# MONGODB_CLUSTER_ADMIN_USER: clusterAdmin                      # Change if you want to use a different username
# MONGODB_CLUSTER_ADMIN_PASSWORD: <CLUSTER-ADMIN-PASSWORD>      # If not provided, the password defaults to value provided in the field MONGODB_DATABASE_ADMIN_PASSWORD
 
# MONGODB_CLUSTER_MONITOR_USER: clusterMonitor                  # Change if you want to use a different username
# MONGODB_CLUSTER_MONITOR_PASSWORD: <CLUSTER-MONITOR-PASSWORD>  # If not provided, the password defaults to value provided in the field MONGODB_DATABASE_ADMIN_PASSWORD
 
# MONGODB_BACKUP_USER: backup                                   # Change if you want to use a different username
# MONGODB_BACKUP_PASSWORD: <BACKUP-USER-PASSWORD>               # If not provided, the password defaults to value provided in the field MONGODB_DATABASE_ADMIN_PASSWORD
---
#
# Secret for supplying the Certificate Authority (CA) certificate issuing the tls key and certificates 
# with which the tls of externally hosted MongoDB server is configured. Accepts only PEM format.
# Not needed if the server certificates are issued by a trusted public CA and not self-signed.
# Name of this secret can be supplied in "spec.mongodb.tlsSecretName" field of Edge CR
#

#apiVersion: v1
#kind: Secret
#metadata:
#  name: external-mongodb-tls-secret       # Name of the secret. Same value should be supplied to "spec.mongodb.tlsSecretName" field of Edge CR
#  namespace: cumulocity-iot-edge          # Replace with the Edge CR name you used
#type: Opaque
#stringData:
#  ca.crt: <CA-CERTIFICATE>                # Replace with the Certificate Authority (CA) certificate in PEM format
