########################################################################################################################
##                                        Defines C8y Edge Custom Resource                                            ##
########################################################################################################################
---
##
## This Custom Resource deploys C8y Edge version 2025.0.2 named 'c8yedge' 
##

apiVersion: edge.cumulocity.com/v1
kind: CumulocityIoTEdge
metadata:
  ## Name of the C8y Edge deployment.
  name: c8yedge
  ## Namespace name into which you installed the Edge operator. By default, the Edge operator is installed in 'c8yedge'.
  namespace: c8yedge
spec:
  ## Edge version you want to install.
  ## For example, 2025.0.0 for 2025 and 2025.0.2 for a fix-2 of 2025.
  version: "2025.0.2"

  ## A fully qualified domain name.
  ## For example, myown.iot.com. Here, you must have the Edge license for the domain name iot.com or myown.iot.com.
  domain: edgebootstrap.example

  ## Edge license key you received for the domain.
  ## To request the license file for Edge, contact support - https://cumulocity.com/docs/additional-resources/contacting-support/
  ##
  ## In the email, you must include
  ## - Your company name, under which the license has been bought
  ## - The domain name (for example, myown.iot.com), where Edge will be reachable
  licenseKey: 7e104191d9042e10652db4822d86365f3b78c19b1cb555b2abe22bce109b5e712b497d9890010a5482ddd4e31487ff6d3d9a9878ad2abb78712cb7649040248c

  ## Name of the “edge” tenant, for example, the company’s name.
  company: Edge Bootstrap

  ## Replace with a valid email, used for admin account.
  email: company@edgebootstrap.example                                    
