########################################################################################################################
#                            Defines the Persistent Volumes with Network File System (NFS)                             #
########################################################################################################################
---
#
# This PV will be claimed by PVC named 'mongod-data-edge-db-rs0-0' in namespace 'c8yedge' for the MongoDB server to store application data.
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: c8yedge-db-pv
spec:
  capacity:
    storage: 75G                                # Modify the capacity to match the value you plan to specify in 'spec.mongodb.resources.requests.storage' field of the Edge CR
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nsf:
    server: <NFS server Hostname or IP Address> # Substitute with NFS server's Hostname or IP Address.
    path: /c8yedge/app-data                     # Path to a folder on NFS

---
#
# This PV will be claimed by PVC named 'microservices-registry-data' in namespace 'c8yedge' for the private docker registry to store microservice images.
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: c8yedge-registry-pv
spec:
  capacity:
    storage: 10G
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <NFS server Hostname or IP Address> # Substitute with NFS server's Hostname or IP Address.
    path: /c8yedge/registry                     # Path to a folder on NFS

---
#
# This PV will be claimed by PVC named 'edge-logs' in namespace 'c8yedge' for the logging component to store the application and system logs.
#
apiVersion: v1
kind: PersistentVolume
metadata:
  name: c8yedge-logs-pv
spec:
  capacity:
    storage: 5G
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: <NFS server Hostname or IP Address> # Substitute with NFS server's Hostname or IP Address.
    path: /c8yedge/logs                         # Path to a folder on NFS
