#######################################################################################
#            Configurations passed to the Helm Chart for Harbor                       #
#######################################################################################
---
#
# These values configure Harbor accessible at 'c8yedge.harbor.local:5001' 
# with self-signed certificates. You can configure with your own CA signed certificates, 
# by changing the 'expose.tls.certSource' to 'secret' and providing 'expose.tls.secret.secretName'
#

expose:
  tls:
    enabled: true
    certSource: auto    # auto: generate the TLS certificate automatically
    auto:
      commonName: c8yedge.harbor.local  # Change the Harbor regsitry domain if necessary
    # certSource: secret  # secret: read the TLS certificate from the specified secret. The TLS certificate can be generated manually or by cert manager
    # secret:
    #   secretName: <SECRET NAME> # The name of secret which contains keys named: tls.crt - the certificate; tls.key - the private key

  type: loadBalancer
  loadBalancer:
    name: c8yedge-harbor-lb
    ports:
      httpsPort: 5001  # Change the Harbor registry port if necessry

externalURL: https://c8yedge.harbor.local:5001  # Harbor regsitry domain and port should match the respective values in expose.tls.auto.commonName and expose.loadBalancer.ports.httpsPort
harborAdminPassword: admin-pass
chartmuseum:
  enabled: true

core:
  image:
    repository: goharbor/harbor-core
    tag: v2.5.6

chartmuseum:
  image:
    repository: goharbor/chartmuseum-photon
    tag: v2.5.6

portal:
  image:
    repository: goharbor/harbor-portal
    tag: v2.10.2
    
jobservice:
  image:
    repository: goharbor/harbor-jobservice
    tag: v2.10.2

nginx:
  image:
    repository: goharbor/nginx-photon
    tag: v2.5.6

notary:
  enabled: false
cache:
  enabled: false
trivy:
  enabled: false
metrics:
  enabled: false
trace:
  enabled: false

# persistence:
#   persistentVolumeClaim:
#     registry:
#       existingClaim:                  # Use the existing PVC which must be created manually before bound, and specify the subPath if the PVC is shared with other components.
#       storageClass:                   # Specify the storageClass used to provision the volume. Or the default StorageClass will be used (the default).
#       size: 5Gi                       # The size of the volume. Default is 5Gi.
#       subPath:                        # The sub path used in the volume. 
#     chartmuseum:
#       existingClaim:                  # Use the existing PVC which must be created manually before bound, and specify the subPath if the PVC is shared with other components.
#       storageClass:                   # Specify the storageClass used to provision the volume. Or the default StorageClass will be used (the default).
#       size: 5Gi                       # The size of the volume. Default is 5Gi.
#       subPath:                        # The sub path used in the volume. 
#     database:
#       existingClaim:                  # Use the existing PVC which must be created manually before bound, and specify the subPath if the PVC is shared with other components.
#       storageClass:                   # Specify the storageClass used to provision the volume. Or the default StorageClass will be used (the default).
#       size: 1Gi                       # The size of the volume. Default is 1Gi.
#       subPath:                        # The sub path used in the volume. 
#     jobservice:
#       jobLog:
#         existingClaim:                # Use the existing PVC which must be created manually before bound, and specify the subPath if the PVC is shared with other components.
#         storageClass:                 # Specify the storageClass used to provision the volume. Or the default StorageClass will be used (the default).
#         size: 1Gi                     # The size of the volume. Default is 1Gi.
#         subPath:                      # The sub path used in the volume. 
#     redis:
#       existingClaim:                  # Use the existing PVC which must be created manually before bound, and specify the subPath if the PVC is shared with other components.
#       storageClass:                   # Specify the storageClass used to provision the volume. Or the default StorageClass will be used (the default).
#       size: 1Gi                       # The size of the volume. Default is 1Gi.
#       subPath:                        # The sub path used in the volume. 
