########################################################################################################################
#                                         Defines Cumulocity IoT Edge Custom Resource                                  #
########################################################################################################################
---
#
# This Custom Resource deploys Cumulocity IoT Edge version 1017.0.0 named 'c8yedge' 
# accessible at myown.iot.com domain with self-signed certificates.
#

apiVersion: edge.cumulocity.com/v1
kind: CumulocityIoTEdge
metadata:
  name: c8yedge						                                        
  namespace: c8yedge                                                        
spec:
  version: "1017.0.0"                                                       
  licenseKey: aacaffe661936cf13bd297f1c27db66405ca639b48e22b62b37c0090f1b521b8f4dd9edb4fed829b1a12db760a707012ba2329e503453d32c4baaa610da38df3

  company: IoT Company                                                      
  domain: myown.iot.com                                                     
  email: myown@iot.com                                                      
