title: "DTM Screenshots"
# The baseUrl is the Cumulocity URL and can be overwritten by the command line argument
# All visit URLs are relative to this baseUrl
baseUrl: "https://dtmdoc.latest.stage.c8y.io"

global:
  capture: viewport
  language: en
  overwrite: true
  login: admin
  timeouts:
    pageLoad: 20000

selectors:
  - treeview.collapseButton.first: ".c8y-tree-view-node .collapse-btn:first"
  - mySelector: "c8y-tree-view-root-node c8y-tree-view-node .c8y-tree-view-node__header__collapse:first"

screenshots:
  - image: "dtm/asset-type/dtm-asset-type-export.png"
    visit: "/apps/digital-twin-manager/index.html#/assetmodels"
    only: false
    actions:
      - click:
          data-cy: "header-bar--main-header-button"
      - click:
          data-cy: "export-asset-models-btn"
          multiple: true
          force: true
      - click:
          selector: ".c8y-tree-view-node .collapse-btn"
          multiple: true
          force: true
      - click:
          selector: ".expanded .c8y-checkbox input:first"
          force: true
      - highlight: mySelector
    tags:
      - export
      - assets

  - image: "dtm/asset-type/dtm-asset-type-import.png"
    visit: "/apps/digital-twin-manager/index.html#/assetmodels"
    only: false
    actions:
      - click:
          data-cy: "import-asset-models-btn"
      - wait: 1000
      - fileUpload: assets/Export-asset-models-2.json
      - wait: 1000
      - click:
          data-cy: next
      - click:
          selector: ".c8y-tree-view-node .collapse-btn"
          multiple: true
          force: true
      - highlight: treeview.collapseButton.first
      - highlight:
          selector: "c8y-stepper-buttons button"
          border:
            "outline-offset": "6px"

  - image: "dtm/asset-type/dtm-asset-type-view.png"
    visit: "/apps/digital-twin-manager/index.html#/assetmodels"
    actions:
      - wait: 1000
      # - text:
      #     selector: "header.navigator-slot-top span"
      #     value: "DTM"
      - highlight: ".navbar-right > :nth-child(-n + 3) > .btn"
      - highlight: ".navigatorContent > :nth-child(4) .link:has(.dlt-c8y-icon-cog, .c8y-icon-enterprise)"
    tags:
      - export
      - assets

  - image: "dtm/asset-type/dtm-asset-type-upload-test.png"
    visit: "/apps/digital-twin-manager/index.html#/assets"
    skip: true
    actions:
      - click: ":nth-child(1) > c8y-tree-view-node > .c8y-tree-view-node > .c8y-tree-view-node__block > .col-md-4 .btn-clean"
      - click: ".d-flex > .btn"
      - fileUpload: assets/Windmills.jpg
      - click: ".card-footer > .btn-primary"

  - image: "dtm/assets/dtm-assets-view-assets.png"
    visit: "/apps/digital-twin-manager/index.html#/assets"
    actions:
      - wait: 1000
      - highlight: ".navigatorContent > :nth-child(3) > .slot > .link"
      - highlight:
          selector: "c8y-tree-view .inner-scroll c8y-tree-view-root-node"
          border:
            "outline-offset": "2px"
          width: 0.25

  - image: "dtm/assets/dtm-assets-asset-hierarchy.png"
    visit: "/apps/digital-twin-manager/index.html#/assets"
    actions:
      - click: "c8y-tree-view-node .collapse-btn:visible:first"
      - click: ".collapse .c8y-checkbox:first"
      - highlight: "c8y-tree-view-node .collapse-btn:visible:first"
      - highlight: "c8y-tree-view-node:has(.collapse-btn:visible:first) button.dropdown-toggle:first"
      - highlight: ".table-data-grid-header-bulk-actions .btnbar"
      - highlight: "c8y-action-bar .btn:first"

  - image: "dtm/assets/dtm-assets-subassets-page.png"
    visit: "/apps/digital-twin-manager/index.html#/assets"
    actions:
      - click: "c8y-tree-view-node:has(.collapse-btn:visible:first) a.btn-clean"
      - wait: 1000
      - highlight: ".navbar-right > :nth-child(-n + 3) > .btn"

  - image: "dtm/assets/dtm-assets-search-assets.png"
    visit: "/apps/digital-twin-manager/index.html#/assets"
    actions:
      - click:
          data-cy: search-input--search-btn
      - wait: 1000
      - highlight:
          selector: "c8y-search-outlet.main-header-item i[c8yicon=search]"
          border:
            "outline-offset": "6px"
      - type:
          selector: "#searchDropdown .c8y-search-form input[type=text]"
          value: "SE"
      - highlight:
          selector: "[data-cy=search-input--asset-table-btn]"
          border:
            "outline-offset": "6px"

  - image: "dtm/assets/dtm-assets-move-assets.png"
    visit: "/apps/digital-twin-manager/index.html#/assets"
    actions:
      - click: "c8y-tree-view-node .collapse-btn:visible:first"
      - click: "c8y-tree-view-node:has(.collapse-btn:visible:first) div[role=group] .c8y-checkbox:first"
      - highlight:
          selector: "c8y-tree-view-node:has(.collapse-btn:visible:first) div[role=group] .c8y-checkbox:first"
          border:
            "outline-offset": "2px"
      - highlight:
          selector: "c8y-tree-view-node:has(.collapse-btn:visible:first) div[role=group] .label-info:first"
          border:
            "outline-offset": "2px"
      - highlight: ".table-data-grid-header-bulk-actions .btnbar button:first"
      - click: ".table-data-grid-header-bulk-actions .btnbar button:first"
      - highlight:
          selector: "c8y-move-assets-modal .modal-footer button"
          border:
            "outline-offset": "6px"
      - highlight:
          selector: "c8y-move-assets-modal .modal-inner-scroll .text-muted"
          border:
            "outline-offset": "2px"

  - image: "dtm/assets/dtm-assets-add-child-asset.png"
    visit: "/apps/digital-twin-manager/index.html#/assets"
    actions:
      - click:
          data-cy: "header-bar--main-header-button"
      - click: "c8y-action-bar button:first"
      - click: "ng-select"
      - click: "ng-dropdown-panel .ng-option:first"
      - highlight: "c8y-asset-hierarchy .c8y-list__item:first"
      - type:
          selector: "c8y-form-group #name"
          value: "SE-TURBINE-101"
      - click: "#assignDevices"
      - click: "[data-cy=c8y-data-grid--row-in-data-grid]:first > .cdk-column-checkbox"
      - click: ".d-col > .card-footer > .btn-primary"
