name: auto-backport
on:
  pull_request_target:
    types: ["labeled", "closed"]

jobs:
  backport:
    name: Backport PR
    runs-on: [ubuntu-latest]
    if: |
      github.event.pull_request.merged == true
      && contains(github.event.pull_request.labels.*.name, 'auto-backport')
      && (
        (github.event.action == 'labeled' && github.event.label.name == 'auto-backport')
        || (github.event.action == 'closed')
      )
    steps:
      - name: Creating github access token
        id: token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.C8Y_DOCS_AUTOMATIONS_APP_ID }}
          private-key: ${{ secrets.C8Y_DOCS_AUTOMATIONS_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          
      - name: Backport Action
        uses: sorenlouv/backport-github-action@929f69d04adbc196d982e60f02837b6cc00b3129
        with:
          github_token: ${{ steps.token.outputs.token }}
          auto_backport_label_prefix: auto-backport-to-
          add_original_reviewers: true

      - name: Info log
        if: ${{ success() }}
        run: cat ~/.backport/backport.info.log

      - name: Debug log
        if: ${{ failure() }}
        run: cat ~/.backport/backport.debug.log
