name: link-check
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JustinBeckwith/linkinator-action@v1.10.4
        with:
          paths: "/home/runner/work/c8y-docs/content"
          concurrency: 1
          markdown: true
