name: Link Checker

on:
 schedule:
  - cron: '0 9 * * 5'
 workflow_dispatch: 
  
permissions:
    contents: read
    pull-requests: write

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install Dependencies
        run: |
          cd broken-links-script
          npm install

      - name: Run Cypress tests
        run: |
          cd broken-links-script
          npm test