name: PDF Generator

on:
  push:
    branches:
      - script_for_generating_PDFs
  workflow_dispatch:  

permissions:
  contents: read

jobs:
  generate-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          path: repo

      - name: Install Hugo CLI
        run: |
          HUGO_VERSION=0.132.2
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          cd repo
          hugo --baseURL "http://localhost:1313/docs/"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install wkhtmltopdf
        run: |
          sudo apt-get update
          sudo apt-get install -y wkhtmltopdf

      - name: Install dependencies
        run: |
          cd repo/pdf-generator
          npm ci

      - name: Generate PDFs
        run: |
          cd repo/pdf-generator
          npm run generate