name: CI
on:
  workflow_dispatch:
  # TODO - restore this, just needed 'pull_request' for testing
  #pull_request_target:
  pull_request:
    types:
      # defaults
      - opened
      - synchronize
      - reopened
      - closed

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.action == 'opened' }}-test
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  PAGES_BRANCH: 'pages/doc'
  TMP_BRANCH: 'TEMP_BRANCH'

jobs:
# Build job
  build:
    name: Build Hugo
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.132.2
    steps:
    - name: Install Hugo CLI
      if: ${{ github.event.pull_request.state != 'closed' }}
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
        && sudo dpkg -i ${{ runner.temp }}/hugo.deb

    - name: Setup base URL env var
      run: |
        echo BASEURL="https://${{ github.repository_owner }}-${{ github.event.repository.name }}-${{ github.job }}-pr-${{ github.event.number }}.surge.sh" >> $GITHUB_ENV

    - name: Report base URL env var
      run: echo "${{ env.BASEURL }}"

    - name: Checkout
      if: ${{ github.event.pull_request.state != 'closed' }}
      uses: actions/checkout@v4
      with:
        ref: refs/pull/${{ github.event.number }}/merge
        submodules: recursive
        fetch-depth: 1
        path: repo

    - name: Build with Hugo
      if: ${{ github.event.pull_request.state != 'closed' }}
      env:
        # For maximum backward compatibility with Hugo modules
        HUGO_ENVIRONMENT: production
        HUGO_ENV: production
      run: |
        cd repo
        hugo \
          --baseURL "${{ env.BASEURL }}/"
        cd ./public
        zip ../../hugo.zip -r *

    - name: Remove repo dir
      if: ${{ github.event.pull_request.state != 'closed' }}
      run: rm -r repo

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
        path: repo

    - name: Set git user
      run: |
        cd repo
        git config user.name "c8y-docs"
        git config user.email "c8y-docs@dev.null"

    - name: Remove old preview
      run: |
        cd repo
        git checkout $PAGES_BRANCH || (git switch --orphan $PAGES_BRANCH && touch README && git commit -a --allow-empty -m "Initial commit")
        git checkout --orphan $TMP_BRANCH
        # remove old PR preview if existing
        rm -r -f ./preview/PR-${{ github.event.number }}/

    - name: Add new preview
      if: ${{ github.event.pull_request.state != 'closed' }}
      run: |
        cd repo
        # create new pr preview folder
        mkdir -p ./preview/PR-${{ github.event.number }}/
        unzip ../hugo.zip -d ./preview/PR-${{ github.event.number }}

    - name: Commit changes
      run: |
        cd repo
        # Add all the files to the temporary branch
        git add -A
        # Commit the changes to the temporary branch
        git commit -am "Update Previews"
    
    - name: Replace branch
      run: |
        cd repo
        # Delete the old branch
        git branch -D $PAGES_BRANCH
        # Rename the temporary branch
        git branch -m $PAGES_BRANCH
    
    - name: Push changes
      run: |
        cd repo
        git push -f origin $PAGES_BRANCH
 

    - name: Run Summary
      if: ${{ github.event.pull_request.state != 'closed' }}
      run: echo "Preview available **[here](${{ env.BASEURL }})**" >> $GITHUB_STEP_SUMMARY

    - name: Add Comment to PR
      if: ${{ github.event.action == 'opened' || github.event.action == 'reopened' }}
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Preview available **[here](${{ env.BASEURL }})**'
          })
