name: CI
on:
  pull_request:
    types:
      # defaults
      - opened
      - synchronize
      - reopened
      - labeled

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
# Build job
  build:
    name: Build Hugo
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.100.1
    steps:
    - name: Install Hugo CLI
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
        && sudo dpkg -i ${{ runner.temp }}/hugo.deb

    - name: Setup base URL env var
      run: |
        echo BASEURL="https://${{ github.event.repository.name }}-${{ github.repository_owner }}-build-preview-pr-${{ github.event.number }}.surge.sh/" >> $GITHUB_ENV

    - name: Report base URL env var
      run: echo "${{ env.BASEURL }}"

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Build with Hugo
      env:
        # For maximum backward compatibility with Hugo modules
        HUGO_ENVIRONMENT: production
        HUGO_ENV: production
      run: |
        hugo \
          --gc \
          --minify \
          --baseURL "${{ env.BASEURL }}"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public

    - name: Deploy to surge                            
      uses: afc163/surge-preview@v1
      id: preview_step
      with:
        surge_token: ${{ secrets.SURGE_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dist: public
        failOnError: false
        teardown: true
        build: |
          echo Deploying to surge.sh
