name: daily-changelogs-dates-trigger
on:
  workflow_dispatch:
  schedule:
    - cron: 00 19 * * *

permissions:
  pull-requests: write
  contents: write

jobs:
  get-component-details:
    name: Get component details from helm charts
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: pipeline-read
    outputs:
      matrix: ${{ steps.component-details.outputs.matrix }}
    steps:
      - name: checkout docs repository
        uses: actions/checkout@v4
        with:
          path: docs
          fetch-depth: 1

      - name: Get GitHub App token
        id: app-token
        uses: Cumulocity-IoT/github-app-token@v1
        with:
            app_id: ${{ secrets.DM_APP_ID }}
            installation_id: ${{ secrets.DM_INSTALLATION_ID }}
            private_key: ${{ secrets.DM_PRIVATE_KEY }}

      - name: Checkout c8y-iot-build-pipeline repository
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.FORKED_REPO }}
          fetch-depth: 1
          ref: ${{ vars.BRANCH }}
          token: ${{ steps.token.outputs.token }}
          path: pipeline

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Get component details from helm charts
        id: component-details
        run: |
          python docs/scripts/get-component-details-from-chart.py
          echo "matrix=$(cat components_to_update.json | jq -c .)" >> $GITHUB_OUTPUT

  trigger-update-changelog:
    uses: ./.github/workflows/update-changelog-dates.yml
    needs: [ get-component-details ]
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-component-details.outputs.matrix) }}
    with:
      version: ${{ matrix.component_version }}
      component: ${{ matrix.component_name }}
      date: ${{ matrix.component_update_date }}