name: Update changelog dates for webapps
on:
  workflow_call:
    inputs:
      component:
        description: 'The name of the component that has been deployed to the environment.'
        required: true
        type: string
      contextPath:
        description: 'The contextPath to get version from environment.'
        required: true
        type: string

permissions:
  pull-requests: write
  contents: write

jobs:
  get-ui-version:
    name: Get currently deployed UI version
    runs-on: ubuntu-latest
    timeout-minutes: 15
    outputs:
      prodVersion: ${{ steps.save-prod-version.outputs.prod-version }}
      date: ${{ steps.get-date.outputs.date }}
    steps:
      - name: Get version of Prod env
        id: save-prod-version
        run: |
          prodVersion=$(curl -k https://demos.eu-latest.cumulocity.com/apps/${{ inputs.contextPath }}/cumulocity.json | jq ".version" | sed  's/"//g')
          echo "${prodVersion}"
          echo "prod-version=${prodVersion}" >> $GITHUB_OUTPUT
      
      - name: Get todays date
        id: get-date
        run: |
          date=$(date '+%Y-%m-%d')
          echo "date=${date}" >> $GITHUB_OUTPUT

  update-changelog:
    uses: ./.github/workflows/update-changelog-dates.yml
    needs: [get-ui-version]
    with:
      version: ${{ needs.get-ui-version.outputs.prodVersion }}
      component: ${{ inputs.component }}
      date: ${{ needs.get-ui-version.outputs.date }}
    secrets: inherit