name: Update changelog dates for webapps trigger
on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  trigger-update-changelog-dates-webapp:
    uses: ./.github/workflows/update-changelog-dates-webapp.yml
    strategy:
      matrix:
        include:
          - component: 'ui-c8y'
            contextPath: 'cockpit'
    with:
      component: ${{ matrix.component }}
      contextPath: ${{ matrix.contextPath }}
    secrets: inherit
